// src/generator/javaShapeActors.ts
import type { GenerateOptions } from "./generator-types.js";

/**
 * تولید فایل ShapeActors.java که شامل همه‌ی actor های شکل هست.
 * کاربر می‌تونه این فایل رو به پروژه اضافه کنه و ازش استفاده کنه.
 */
export function generateShapeActorsJava(packageName?: string): string {
	const lines: string[] = [];

	if (packageName) {
		lines.push(`package ${packageName};`);
		lines.push("");
	}

	lines.push(`import com.badlogic.gdx.graphics.Color;`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.Batch;`);
	lines.push(`import com.badlogic.gdx.graphics.glutils.ShapeRenderer;`);
	lines.push(`import com.badlogic.gdx.math.MathUtils;`);
	lines.push(`import com.badlogic.gdx.scenes.scene2d.Actor;`);
	lines.push("");
	lines.push(`/**`);
	lines.push(` * Auto-generated by LibGDX Editor.`);
	lines.push(` * Simple shape actors that draw themselves using ShapeRenderer.`);
	lines.push(` *`);
	lines.push(` * Usage:`);
	lines.push(` *   ShapeRenderer shapes = new ShapeRenderer();`);
	lines.push(` *   RectangleActor rect = new RectangleActor(64, 64);`);
	lines.push(` *   rect.setColor(Color.RED);`);
	lines.push(` *   stage.addActor(rect);`);
	lines.push(` *`);
	lines.push(` * NOTE: In your render loop, you must call:`);
	lines.push(` *   shapes.setProjectionMatrix(stage.getCamera().combined);`);
	lines.push(` *   shapes.begin(ShapeRenderer.ShapeType.Filled);`);
	lines.push(` *   shapes.end();`);
	lines.push(` * Because Scene2D actors don't have direct access to ShapeRenderer.`);
	lines.push(` *`);
	lines.push(` * Alternative: Use these actors with a ShapeRenderer-based Stage renderer.`);
	lines.push(` */`);
	lines.push(`public class ShapeActors {`);
	lines.push(`\tprivate ShapeActors() {} // static helper class`);
	lines.push("");
	lines.push(`\t/** Shared ShapeRenderer — set this once at game start */`);
	lines.push(`\tpublic static ShapeRenderer sharedRenderer = null;`);
	lines.push("");

	// ============================================================
	// Base Shape Actor
	// ============================================================
	lines.push(`\t// ============================================================`);
	lines.push(`\t// Base Shape Actor`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static abstract class ShapeActor extends Actor {`);
	lines.push(`\t\tprotected final Color shapeColor = new Color(1, 1, 1, 1);`);
	lines.push(`\t\tprotected boolean filled = true;`);
	lines.push(`\t\tprotected float strokeWidth = 2f;`);
	lines.push("");
	lines.push(`\t\tpublic ShapeActor(float width, float height) {`);
	lines.push(`\t\t\tsetSize(width, height);`);
	lines.push(`\t\t\tsetOrigin(width / 2f, height / 2f);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tpublic void setShapeColor(Color color) {`);
	lines.push(`\t\t\tshapeColor.set(color);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tpublic Color getShapeColor() {`);
	lines.push(`\t\t\treturn shapeColor;`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tpublic void setFilled(boolean filled) {`);
	lines.push(`\t\t\tthis.filled = filled;`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tpublic boolean isFilled() {`);
	lines.push(`\t\t\treturn filled;`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tpublic void setStrokeWidth(float width) {`);
	lines.push(`\t\t\tthis.strokeWidth = width;`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tpublic void draw(Batch batch, float parentAlpha) {`);
	lines.push(`\t\t\tif (sharedRenderer == null) return;`);
	lines.push("");
	lines.push(`\t\t\t// flush batch first, then draw shape`);
	lines.push(`\t\t\tbatch.end();`);
	lines.push("");
	lines.push(`\t\t\tsharedRenderer.setProjectionMatrix(batch.getProjectionMatrix());`);
	lines.push(`\t\t\tsharedRenderer.setTransformMatrix(batch.getTransformMatrix());`);
	lines.push("");
	lines.push(`\t\t\tfloat alpha = parentAlpha * getColor().a * shapeColor.a;`);
	lines.push("");
	lines.push(`\t\t\tif (filled) {`);
	lines.push(`\t\t\t\tsharedRenderer.setColor(shapeColor.r, shapeColor.g, shapeColor.b, alpha);`);
	lines.push(`\t\t\t\tsharedRenderer.begin(ShapeRenderer.ShapeType.Filled);`);
	lines.push(`\t\t\t\tdrawFilled(sharedRenderer);`);
	lines.push(`\t\t\t\tsharedRenderer.end();`);
	lines.push(`\t\t\t} else {`);
	lines.push(`\t\t\t\tsharedRenderer.setColor(shapeColor.r, shapeColor.g, shapeColor.b, alpha);`);
	lines.push(`\t\t\t\tsharedRenderer.begin(ShapeRenderer.ShapeType.Line);`);
	lines.push(`\t\t\t\tdrawOutline(sharedRenderer);`);
	lines.push(`\t\t\t\tsharedRenderer.end();`);
	lines.push(`\t\t\t}`);
	lines.push("");
	lines.push(`\t\t\tbatch.begin();`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tprotected abstract void drawFilled(ShapeRenderer r);`);
	lines.push(`\t\tprotected abstract void drawOutline(ShapeRenderer r);`);
	lines.push("");
	lines.push(`\t\tprotected float worldX() { return getX(); }`);
	lines.push(`\t\tprotected float worldY() { return getY(); }`);
	lines.push(`\t\tprotected float worldW() { return getWidth() * getScaleX(); }`);
	lines.push(`\t\tprotected float worldH() { return getHeight() * getScaleY(); }`);
	lines.push(`\t}`);
	lines.push("");

	// ============================================================
	// RectangleActor
	// ============================================================
	lines.push(`\t// ============================================================`);
	lines.push(`\t// Rectangle`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static class RectangleActor extends ShapeActor {`);
	lines.push(`\t\tpublic RectangleActor(float width, float height) {`);
	lines.push(`\t\t\tsuper(width, height);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawFilled(ShapeRenderer r) {`);
	lines.push(`\t\t\tr.rect(worldX(), worldY(), worldW(), worldH());`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawOutline(ShapeRenderer r) {`);
	lines.push(`\t\t\tr.rect(worldX(), worldY(), worldW(), worldH());`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	// ============================================================
	// CircleActor
	// ============================================================
	lines.push(`\t// ============================================================`);
	lines.push(`\t// Circle / Ellipse`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static class CircleActor extends ShapeActor {`);
	lines.push(`\t\tpublic CircleActor(float width, float height) {`);
	lines.push(`\t\t\tsuper(width, height);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawFilled(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat cx = worldX() + worldW() / 2f;`);
	lines.push(`\t\t\tfloat cy = worldY() + worldH() / 2f;`);
	lines.push(`\t\t\tfloat rx = worldW() / 2f;`);
	lines.push(`\t\t\tfloat ry = worldH() / 2f;`);
	lines.push(`\t\t\tr.ellipse(cx - rx, cy - ry, rx * 2f, ry * 2f);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawOutline(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat cx = worldX() + worldW() / 2f;`);
	lines.push(`\t\t\tfloat cy = worldY() + worldH() / 2f;`);
	lines.push(`\t\t\tfloat rx = worldW() / 2f;`);
	lines.push(`\t\t\tfloat ry = worldH() / 2f;`);
	lines.push(`\t\t\tr.ellipse(cx - rx, cy - ry, rx * 2f, ry * 2f);`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	// ============================================================
	// TriangleActor
	// ============================================================
	lines.push(`\t// ============================================================`);
	lines.push(`\t// Triangle`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static class TriangleActor extends ShapeActor {`);
	lines.push(`\t\tpublic TriangleActor(float width, float height) {`);
	lines.push(`\t\t\tsuper(width, height);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tprivate float[] points() {`);
	lines.push(`\t\t\tfloat x = worldX(), y = worldY(), w = worldW(), h = worldH();`);
	lines.push(`\t\t\t// top-center, bottom-right, bottom-left`);
	lines.push(`\t\t\treturn new float[] { x + w / 2f, y + h, x + w, y, x, y };`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawFilled(ShapeRenderer r) {`);
	lines.push(`\t\t\tr.triangle(points()[0], points()[1], points()[2], points()[3], points()[4], points()[5]);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawOutline(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat[] p = points();`);
	lines.push(`\t\t\tr.triangle(p[0], p[1], p[2], p[3], p[4], p[5]);`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	// ============================================================
	// DiamondActor
	// ============================================================
	lines.push(`\t// ============================================================`);
	lines.push(`\t// Diamond`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static class DiamondActor extends ShapeActor {`);
	lines.push(`\t\tpublic DiamondActor(float width, float height) {`);
	lines.push(`\t\t\tsuper(width, height);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tprivate float[] points() {`);
	lines.push(`\t\t\tfloat x = worldX(), y = worldY(), w = worldW(), h = worldH();`);
	lines.push(`\t\t\tfloat cx = x + w / 2f, cy = y + h / 2f;`);
	lines.push(`\t\t\t// top, right, bottom, left`);
	lines.push(`\t\t\treturn new float[] { cx, y + h, x + w, cy, cx, y, x, cy };`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawFilled(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat[] p = points();`);
	lines.push(`\t\t\tr.triangle(p[0], p[1], p[2], p[3], p[6], p[7]);`);
	lines.push(`\t\t\tr.triangle(p[2], p[3], p[4], p[5], p[6], p[7]);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawOutline(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat[] p = points();`);
	lines.push(`\t\t\tr.line(p[0], p[1], p[2], p[3]);`);
	lines.push(`\t\t\tr.line(p[2], p[3], p[4], p[5]);`);
	lines.push(`\t\t\tr.line(p[4], p[5], p[6], p[7]);`);
	lines.push(`\t\t\tr.line(p[6], p[7], p[0], p[1]);`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	// ============================================================
	// PolygonActor (پایه برای pentagon/hexagon)
	// ============================================================
	lines.push(`\t// ============================================================`);
	lines.push(`\t// Regular Polygon (base for Pentagon/Hexagon)`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static abstract class RegularPolygonActor extends ShapeActor {`);
	lines.push(`\t\tprotected final int sides;`);
	lines.push(`\t\tprotected final float startAngle;`);
	lines.push("");
	lines.push(`\t\tpublic RegularPolygonActor(float width, float height, int sides, float startAngleDeg) {`);
	lines.push(`\t\t\tsuper(width, height);`);
	lines.push(`\t\t\tthis.sides = sides;`);
	lines.push(`\t\t\tthis.startAngle = startAngleDeg * MathUtils.degreesToRadians;`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tprotected float[] computeVertices() {`);
	lines.push(`\t\t\tfloat cx = worldX() + worldW() / 2f;`);
	lines.push(`\t\t\tfloat cy = worldY() + worldH() / 2f;`);
	lines.push(`\t\t\tfloat r = Math.min(worldW(), worldH()) / 2f;`);
	lines.push(`\t\t\tfloat[] verts = new float[sides * 2];`);
	lines.push(`\t\t\tfor (int i = 0; i < sides; i++) {`);
	lines.push(`\t\t\t\tfloat angle = startAngle + i * MathUtils.PI2 / sides;`);
	lines.push(`\t\t\t\tverts[i * 2] = cx + MathUtils.cos(angle) * r;`);
	lines.push(`\t\t\t\tverts[i * 2 + 1] = cy + MathUtils.sin(angle) * r;`);
	lines.push(`\t\t\t}`);
	lines.push(`\t\t\treturn verts;`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawFilled(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat[] v = computeVertices();`);
	lines.push(`\t\t\t// fan triangulation from first vertex`);
	lines.push(`\t\t\tfor (int i = 1; i < sides - 1; i++) {`);
	lines.push(`\t\t\t\tr.triangle(v[0], v[1], v[i * 2], v[i * 2 + 1], v[(i + 1) * 2], v[(i + 1) * 2 + 1]);`);
	lines.push(`\t\t\t}`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawOutline(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat[] v = computeVertices();`);
	lines.push(`\t\t\tfor (int i = 0; i < sides; i++) {`);
	lines.push(`\t\t\t\tint j = (i + 1) % sides;`);
	lines.push(`\t\t\t\tr.line(v[i * 2], v[i * 2 + 1], v[j * 2], v[j * 2 + 1]);`);
	lines.push(`\t\t\t}`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	lines.push(`\t// ============================================================`);
	lines.push(`\t// Pentagon`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static class PentagonActor extends RegularPolygonActor {`);
	lines.push(`\t\tpublic PentagonActor(float width, float height) {`);
	lines.push(`\t\t\tsuper(width, height, 5, 90f);`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	lines.push(`\t// ============================================================`);
	lines.push(`\t// Hexagon`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static class HexagonActor extends RegularPolygonActor {`);
	lines.push(`\t\tpublic HexagonActor(float width, float height) {`);
	lines.push(`\t\t\tsuper(width, height, 6, 0f);`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	// ============================================================
	// StarActor
	// ============================================================
	lines.push(`\t// ============================================================`);
	lines.push(`\t// Star`);
	lines.push(`\t// ============================================================`);
	lines.push("");
	lines.push(`\tpublic static class StarActor extends ShapeActor {`);
	lines.push(`\t\tprivate final int points = 5;`);
	lines.push(`\t\tprivate final float innerRatio = 0.45f;`);
	lines.push("");
	lines.push(`\t\tpublic StarActor(float width, float height) {`);
	lines.push(`\t\t\tsuper(width, height);`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\tprivate float[] computeVertices() {`);
	lines.push(`\t\t\tfloat cx = worldX() + worldW() / 2f;`);
	lines.push(`\t\t\tfloat cy = worldY() + worldH() / 2f;`);
	lines.push(`\t\t\tfloat outerR = Math.min(worldW(), worldH()) / 2f;`);
	lines.push(`\t\t\tfloat innerR = outerR * innerRatio;`);
	lines.push(`\t\t\tfloat startAngle = 90f * MathUtils.degreesToRadians;`);
	lines.push(`\t\t\tint vertCount = points * 2;`);
	lines.push(`\t\t\tfloat[] verts = new float[vertCount * 2];`);
	lines.push(`\t\t\tfor (int i = 0; i < vertCount; i++) {`);
	lines.push(`\t\t\t\tfloat r = (i % 2 == 0) ? outerR : innerR;`);
	lines.push(`\t\t\t\tfloat angle = startAngle + i * MathUtils.PI / points;`);
	lines.push(`\t\t\t\tverts[i * 2] = cx + MathUtils.cos(angle) * r;`);
	lines.push(`\t\t\t\tverts[i * 2 + 1] = cy + MathUtils.sin(angle) * r;`);
	lines.push(`\t\t\t}`);
	lines.push(`\t\t\treturn verts;`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawFilled(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat[] v = computeVertices();`);
	lines.push(`\t\t\tint vertCount = points * 2;`);
	lines.push(`\t\t\tfor (int i = 1; i < vertCount - 1; i++) {`);
	lines.push(`\t\t\t\tr.triangle(v[0], v[1], v[i * 2], v[i * 2 + 1], v[(i + 1) * 2], v[(i + 1) * 2 + 1]);`);
	lines.push(`\t\t\t}`);
	lines.push(`\t\t}`);
	lines.push("");
	lines.push(`\t\t@Override`);
	lines.push(`\t\tprotected void drawOutline(ShapeRenderer r) {`);
	lines.push(`\t\t\tfloat[] v = computeVertices();`);
	lines.push(`\t\t\tint vertCount = points * 2;`);
	lines.push(`\t\t\tfor (int i = 0; i < vertCount; i++) {`);
	lines.push(`\t\t\t\tint j = (i + 1) % vertCount;`);
	lines.push(`\t\t\t\tr.line(v[i * 2], v[i * 2 + 1], v[j * 2], v[j * 2 + 1]);`);
	lines.push(`\t\t\t}`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");

	lines.push(`}`);
	lines.push("");

	return lines.join("\n");
}

// ============================================================
// File wrapper
// ============================================================

export function generateShapeActorsFile(options: GenerateOptions): { fileName: string; content: string } {
	const ext = options.language === "java" ? "java" : "kt";
	const content = options.language === "java" ? generateShapeActorsJava(options.helperPackageName) : generateShapeActorsKotlin(options.helperPackageName);

	return {
		fileName: `ShapeActors.${ext}`,
		content,
	};
}

// ============================================================
// Kotlin version (ساده‌تر)
// ============================================================

function generateShapeActorsKotlin(packageName?: string): string {
	const lines: string[] = [];

	if (packageName) {
		lines.push(`package ${packageName}`);
		lines.push("");
	}

	lines.push(`import com.badlogic.gdx.graphics.Color`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.Batch`);
	lines.push(`import com.badlogic.gdx.graphics.glutils.ShapeRenderer`);
	lines.push(`import com.badlogic.gdx.math.MathUtils`);
	lines.push(`import com.badlogic.gdx.scenes.scene2d.Actor`);
	lines.push("");
	lines.push(`/**`);
	lines.push(` * Auto-generated by LibGDX Editor.`);
	lines.push(` * Simple shape actors that draw themselves using ShapeRenderer.`);
	lines.push(` *`);
	lines.push(` * NOTE: In your render loop, make sure to call:`);
	lines.push(` *   ShapeActors.sharedRenderer.setProjectionMatrix(stage.camera.combined)`);
	lines.push(` */`);
	lines.push(`object ShapeActors {`);
	lines.push(`    @JvmStatic var sharedRenderer: ShapeRenderer? = null`);
	lines.push("");
	lines.push(`    abstract class ShapeActor(width: Float, height: Float) : Actor() {`);
	lines.push(`        val shapeColor = Color(1f, 1f, 1f, 1f)`);
	lines.push(`        var filled = true`);
	lines.push(`        var strokeWidth = 2f`);
	lines.push("");
	lines.push(`        init {`);
	lines.push(`            setSize(width, height)`);
	lines.push(`            setOrigin(width / 2f, height / 2f)`);
	lines.push(`        }`);
	lines.push("");
	lines.push(`        override fun draw(batch: Batch, parentAlpha: Float) {`);
	lines.push(`            val r = sharedRenderer ?: return`);
	lines.push(`            batch.end()`);
	lines.push(`            r.projectionMatrix = batch.projectionMatrix`);
	lines.push(`            r.transformMatrix = batch.transformMatrix`);
	lines.push(`            val alpha = parentAlpha * color.a * shapeColor.a`);
	lines.push(`            r.color = Color(shapeColor.r, shapeColor.g, shapeColor.b, alpha)`);
	lines.push(`            if (filled) {`);
	lines.push(`                r.begin(ShapeRenderer.ShapeType.Filled)`);
	lines.push(`                drawFilled(r)`);
	lines.push(`                r.end()`);
	lines.push(`            } else {`);
	lines.push(`                r.begin(ShapeRenderer.ShapeType.Line)`);
	lines.push(`                drawOutline(r)`);
	lines.push(`                r.end()`);
	lines.push(`            }`);
	lines.push(`            batch.begin()`);
	lines.push(`        }`);
	lines.push("");
	lines.push(`        protected abstract fun drawFilled(r: ShapeRenderer)`);
	lines.push(`        protected abstract fun drawOutline(r: ShapeRenderer)`);
	lines.push("");
	lines.push(`        protected val worldX: Float get() = x`);
	lines.push(`        protected val worldY: Float get() = y`);
	lines.push(`        protected val worldW: Float get() = width * scaleX`);
	lines.push(`        protected val worldH: Float get() = height * scaleY`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    class RectangleActor(width: Float, height: Float) : ShapeActor(width, height) {`);
	lines.push(`        override fun drawFilled(r: ShapeRenderer) = r.rect(worldX, worldY, worldW, worldH)`);
	lines.push(`        override fun drawOutline(r: ShapeRenderer) = r.rect(worldX, worldY, worldW, worldH)`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    class CircleActor(width: Float, height: Float) : ShapeActor(width, height) {`);
	lines.push(`        override fun drawFilled(r: ShapeRenderer) {`);
	lines.push(`            r.ellipse(worldX, worldY, worldW, worldH)`);
	lines.push(`        }`);
	lines.push(`        override fun drawOutline(r: ShapeRenderer) {`);
	lines.push(`            r.ellipse(worldX, worldY, worldW, worldH)`);
	lines.push(`        }`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    class TriangleActor(width: Float, height: Float) : ShapeActor(width, height) {`);
	lines.push(`        override fun drawFilled(r: ShapeRenderer) {`);
	lines.push(`            r.triangle(worldX + worldW / 2f, worldY + worldH, worldX + worldW, worldY, worldX, worldY)`);
	lines.push(`        }`);
	lines.push(`        override fun drawOutline(r: ShapeRenderer) {`);
	lines.push(`            r.triangle(worldX + worldW / 2f, worldY + worldH, worldX + worldW, worldY, worldX, worldY)`);
	lines.push(`        }`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    class DiamondActor(width: Float, height: Float) : ShapeActor(width, height) {`);
	lines.push(`        override fun drawFilled(r: ShapeRenderer) {`);
	lines.push(`            val cx = worldX + worldW / 2f`);
	lines.push(`            val cy = worldY + worldH / 2f`);
	lines.push(`            r.triangle(cx, worldY + worldH, worldX + worldW, cy, worldX, cy)`);
	lines.push(`            r.triangle(worldX + worldW, cy, cx, worldY, worldX, cy)`);
	lines.push(`        }`);
	lines.push(`        override fun drawOutline(r: ShapeRenderer) {`);
	lines.push(`            val cx = worldX + worldW / 2f`);
	lines.push(`            val cy = worldY + worldH / 2f`);
	lines.push(`            r.line(cx, worldY + worldH, worldX + worldW, cy)`);
	lines.push(`            r.line(worldX + worldW, cy, cx, worldY)`);
	lines.push(`            r.line(cx, worldY, worldX, cy)`);
	lines.push(`            r.line(worldX, cy, cx, worldY + worldH)`);
	lines.push(`        }`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    class PentagonActor(width: Float, height: Float) : RegularPolygonActor(width, height, 5, 90f)`);
	lines.push(`    class HexagonActor(width: Float, height: Float) : RegularPolygonActor(width, height, 6, 0f)`);
	lines.push("");
	lines.push(`    abstract class RegularPolygonActor(width: Float, height: Float, protected val sides: Int, startAngleDeg: Float) : ShapeActor(width, height) {`);
	lines.push(`        private val startAngle = startAngleDeg * MathUtils.degreesToRadians`);
	lines.push("");
	lines.push(`        protected fun computeVertices(): FloatArray {`);
	lines.push(`            val cx = worldX + worldW / 2f`);
	lines.push(`            val cy = worldY + worldH / 2f`);
	lines.push(`            val r = minOf(worldW, worldH) / 2f`);
	lines.push(`            val verts = FloatArray(sides * 2)`);
	lines.push(`            for (i in 0 until sides) {`);
	lines.push(`                val angle = startAngle + i * MathUtils.PI2 / sides`);
	lines.push(`                verts[i * 2] = cx + MathUtils.cos(angle) * r`);
	lines.push(`                verts[i * 2 + 1] = cy + MathUtils.sin(angle) * r`);
	lines.push(`            }`);
	lines.push(`            return verts`);
	lines.push(`        }`);
	lines.push("");
	lines.push(`        override fun drawFilled(r: ShapeRenderer) {`);
	lines.push(`            val v = computeVertices()`);
	lines.push(`            for (i in 1 until sides - 1) {`);
	lines.push(`                r.triangle(v[0], v[1], v[i * 2], v[i * 2 + 1], v[(i + 1) * 2], v[(i + 1) * 2 + 1])`);
	lines.push(`            }`);
	lines.push(`        }`);
	lines.push("");
	lines.push(`        override fun drawOutline(r: ShapeRenderer) {`);
	lines.push(`            val v = computeVertices()`);
	lines.push(`            for (i in 0 until sides) {`);
	lines.push(`                val j = (i + 1) % sides`);
	lines.push(`                r.line(v[i * 2], v[i * 2 + 1], v[j * 2], v[j * 2 + 1])`);
	lines.push(`            }`);
	lines.push(`        }`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    class StarActor(width: Float, height: Float) : ShapeActor(width, height) {`);
	lines.push(`        private val points = 5`);
	lines.push(`        private val innerRatio = 0.45f`);
	lines.push("");
	lines.push(`        private fun computeVertices(): FloatArray {`);
	lines.push(`            val cx = worldX + worldW / 2f`);
	lines.push(`            val cy = worldY + worldH / 2f`);
	lines.push(`            val outerR = minOf(worldW, worldH) / 2f`);
	lines.push(`            val innerR = outerR * innerRatio`);
	lines.push(`            val startAngle = 90f * MathUtils.degreesToRadians`);
	lines.push(`            val vertCount = points * 2`);
	lines.push(`            val verts = FloatArray(vertCount * 2)`);
	lines.push(`            for (i in 0 until vertCount) {`);
	lines.push(`                val r = if (i % 2 == 0) outerR else innerR`);
	lines.push(`                val angle = startAngle + i * MathUtils.PI / points`);
	lines.push(`                verts[i * 2] = cx + MathUtils.cos(angle) * r`);
	lines.push(`                verts[i * 2 + 1] = cy + MathUtils.sin(angle) * r`);
	lines.push(`            }`);
	lines.push(`            return verts`);
	lines.push(`        }`);
	lines.push("");
	lines.push(`        override fun drawFilled(r: ShapeRenderer) {`);
	lines.push(`            val v = computeVertices()`);
	lines.push(`            val vertCount = points * 2`);
	lines.push(`            for (i in 1 until vertCount - 1) {`);
	lines.push(`                r.triangle(v[0], v[1], v[i * 2], v[i * 2 + 1], v[(i + 1) * 2], v[(i + 1) * 2 + 1])`);
	lines.push(`            }`);
	lines.push(`        }`);
	lines.push("");
	lines.push(`        override fun drawOutline(r: ShapeRenderer) {`);
	lines.push(`            val v = computeVertices()`);
	lines.push(`            val vertCount = points * 2`);
	lines.push(`            for (i in 0 until vertCount) {`);
	lines.push(`                val j = (i + 1) % vertCount`);
	lines.push(`                r.line(v[i * 2], v[i * 2 + 1], v[j * 2], v[j * 2 + 1])`);
	lines.push(`            }`);
	lines.push(`        }`);
	lines.push(`    }`);
	lines.push(`}`);
	lines.push("");

	return lines.join("\n");
}
