// src/generator/javaAnimatedActor.ts
import type { GenerateOptions } from "./generator-types.js";

export function generateAnimatedActorJava(packageName?: string): string {
	const lines: string[] = [];

	if (packageName) {
		lines.push(`package ${packageName};`);
		lines.push("");
	}

	lines.push(`import com.badlogic.gdx.graphics.g2d.Animation;`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.Batch;`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.TextureRegion;`);
	lines.push(`import com.badlogic.gdx.scenes.scene2d.Actor;`);
	lines.push("");
	lines.push(`/**`);
	lines.push(` * Auto-generated by LibGDX Editor.`);
	lines.push(` * A simple Scene2D actor that plays a libGDX Animation.`);
	lines.push(` */`);
	lines.push(`public class AnimatedActor extends Actor {`);
	lines.push(`\tprivate Animation<TextureRegion> animation;`);
	lines.push(`\tprivate float stateTime = 0f;`);
	lines.push(`\tprivate boolean playing = true;`);
	lines.push(`\tprivate boolean looping = true;`);
	lines.push("");
	lines.push(`\tpublic AnimatedActor(Animation<TextureRegion> animation) {`);
	lines.push(`\t\tthis.animation = animation;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic Animation<TextureRegion> getAnimation() {`);
	lines.push(`\t\treturn animation;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void setAnimation(Animation<TextureRegion> animation) {`);
	lines.push(`\t\tthis.animation = animation;`);
	lines.push(`\t\tthis.stateTime = 0f;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void setPlaying(boolean playing) {`);
	lines.push(`\t\tthis.playing = playing;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic boolean isPlaying() {`);
	lines.push(`\t\treturn playing;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void setLooping(boolean looping) {`);
	lines.push(`\t\tthis.looping = looping;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic boolean isLooping() {`);
	lines.push(`\t\treturn looping;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void reset() {`);
	lines.push(`\t\tstateTime = 0f;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\t@Override`);
	lines.push(`\tpublic void act(float delta) {`);
	lines.push(`\t\tsuper.act(delta);`);
	lines.push(`\t\tif (playing) {`);
	lines.push(`\t\t\tstateTime += delta;`);
	lines.push(`\t\t}`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\t@Override`);
	lines.push(`\tpublic void draw(Batch batch, float parentAlpha) {`);
	lines.push(`\t\tif (animation == null) return;`);
	lines.push(`\t\tTextureRegion frame = animation.getKeyFrame(stateTime, looping);`);
	lines.push(`\t\tbatch.setColor(getColor().r, getColor().g, getColor().b, getColor().a * parentAlpha);`);
	lines.push(`\t\tbatch.draw(frame,`);
	lines.push(`\t\t\tgetX(), getY(),`);
	lines.push(`\t\t\tgetOriginX(), getOriginY(),`);
	lines.push(`\t\t\tgetWidth(), getHeight(),`);
	lines.push(`\t\t\tgetScaleX(), getScaleY(),`);
	lines.push(`\t\t\tgetRotation()`);
	lines.push(`\t\t);`);
	lines.push(`\t}`);
	lines.push(`}`);

	return lines.join("\n");
}

export function generateAnimatedActorKotlin(packageName?: string): string {
	const lines: string[] = [];

	if (packageName) {
		lines.push(`package ${packageName}`);
		lines.push("");
	}

	lines.push(`import com.badlogic.gdx.graphics.g2d.Animation`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.Batch`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.TextureRegion`);
	lines.push(`import com.badlogic.gdx.scenes.scene2d.Actor`);
	lines.push("");
	lines.push(`/**`);
	lines.push(` * Auto-generated by LibGDX Editor.`);
	lines.push(` * A simple Scene2D actor that plays a libGDX Animation.`);
	lines.push(` */`);
	lines.push(`class AnimatedActor(var animation: Animation<TextureRegion>?) : Actor() {`);
	lines.push(`    private var stateTime = 0f`);
	lines.push(`    var playing = true`);
	lines.push(`    var looping = true`);
	lines.push("");
	lines.push(`    fun reset() {`);
	lines.push(`        stateTime = 0f`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    override fun act(delta: Float) {`);
	lines.push(`        super.act(delta)`);
	lines.push(`        if (playing) stateTime += delta`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    override fun draw(batch: Batch, parentAlpha: Float) {`);
	lines.push(`        val anim = animation ?: return`);
	lines.push(`        val frame = anim.getKeyFrame(stateTime, looping)`);
	lines.push(`        batch.color = color`);
	lines.push(`        batch.draw(frame, x, y, originX, originY, width, height, scaleX, scaleY, rotation)`);
	lines.push(`    }`);
	lines.push(`}`);

	return lines.join("\n");
}

export function generateAnimatedActorFile(options: GenerateOptions): { fileName: string; content: string } {
	const ext = options.language === "java" ? "java" : "kt";
	const content = options.language === "java" ? generateAnimatedActorJava(options.helperPackageName) : generateAnimatedActorKotlin(options.helperPackageName);

	return {
		fileName: `AnimatedActor.${ext}`,
		content,
	};
}
