// src/generator/javaLabelActor.ts
import type { GenerateOptions } from "./generator-types.js";

/**
 * تولید LabelActors.java — یه Actor ساده برای متن با BitmapFont.
 * بدون نیاز به Skin — کاربر فقط یه BitmapFont می‌ده.
 */
export function generateLabelActorJava(packageName?: string): string {
	const lines: string[] = [];

	if (packageName) {
		lines.push(`package ${packageName};`);
		lines.push("");
	}

	lines.push(`import com.badlogic.gdx.graphics.Color;`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.Batch;`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.BitmapFont;`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.GlyphLayout;`);
	lines.push(`import com.badlogic.gdx.scenes.scene2d.Actor;`);
	lines.push(`import com.badlogic.gdx.utils.Align;`);
	lines.push("");
	lines.push(`/**`);
	lines.push(` * Auto-generated by LibGDX Editor.`);
	lines.push(` * Simple Label actor using BitmapFont (no Skin required).`);
	lines.push(` *`);
	lines.push(` * Usage:`);
	lines.push(` *   BitmapFont font = new BitmapFont();`);
	lines.push(` *   LabelActor label = new LabelActor("Hello", font);`);
	lines.push(` *   label.setTextColor(Color.WHITE);`);
	lines.push(` *   stage.addActor(label);`);
	lines.push(` */`);
	lines.push(`public class LabelActor extends Actor {`);
	lines.push(`\tprivate CharSequence text;`);
	lines.push(`\tprivate final BitmapFont font;`);
	lines.push(`\tprivate final Color textColor = new Color(1, 1, 1, 1);`);
	lines.push(`\tprivate final GlyphLayout layout = new GlyphLayout();`);
	lines.push(`\tprivate int alignment = Align.left;`);
	lines.push("");
	lines.push(`\tpublic LabelActor(CharSequence text, BitmapFont font) {`);
	lines.push(`\t\tthis.text = text;`);
	lines.push(`\t\tthis.font = font;`);
	lines.push(`\t\tupdateSize();`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void setText(CharSequence newText) {`);
	lines.push(`\t\tthis.text = newText;`);
	lines.push(`\t\tupdateSize();`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic CharSequence getText() {`);
	lines.push(`\t\treturn text;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void setTextColor(Color color) {`);
	lines.push(`\t\tthis.textColor.set(color);`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic Color getTextColor() {`);
	lines.push(`\t\treturn textColor;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void setAlignment(int align) {`);
	lines.push(`\t\tthis.alignment = align;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic BitmapFont getFont() {`);
	lines.push(`\t\treturn font;`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tpublic void setFontScale(float scale) {`);
	lines.push(`\t\tfont.getData().setScale(scale);`);
	lines.push(`\t\tupdateSize();`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\tprivate void updateSize() {`);
	lines.push(`\t\tif (text == null || font == null) return;`);
	lines.push(`\t\tlayout.setText(font, text, textColor, 0, alignment, false);`);
	lines.push(`\t\tsetSize(layout.width, layout.height);`);
	lines.push(`\t}`);
	lines.push("");
	lines.push(`\t@Override`);
	lines.push(`\tpublic void draw(Batch batch, float parentAlpha) {`);
	lines.push(`\t\tif (text == null || font == null) return;`);
	lines.push(`\t\tColor prev = font.getColor();`);
	lines.push(`\t\tfont.setColor(textColor.r, textColor.g, textColor.b, textColor.a * parentAlpha);`);
	lines.push(`\t\tfont.draw(batch, text, getX(), getY() + getHeight(), 0, alignment, false);`);
	lines.push(`\t\tfont.setColor(prev);`);
	lines.push(`\t}`);
	lines.push(`}`);
	lines.push("");

	return lines.join("\n");
}

export function generateLabelActorKotlin(packageName?: string): string {
	const lines: string[] = [];

	if (packageName) {
		lines.push(`package ${packageName}`);
		lines.push("");
	}

	lines.push(`import com.badlogic.gdx.graphics.Color`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.Batch`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.BitmapFont`);
	lines.push(`import com.badlogic.gdx.graphics.g2d.GlyphLayout`);
	lines.push(`import com.badlogic.gdx.scenes.scene2d.Actor`);
	lines.push(`import com.badlogic.gdx.utils.Align`);
	lines.push("");
	lines.push(`/**`);
	lines.push(` * Auto-generated by LibGDX Editor.`);
	lines.push(` * Simple Label actor using BitmapFont (no Skin required).`);
	lines.push(` */`);
	lines.push(`class LabelActor(var text: CharSequence, private val font: BitmapFont) : Actor() {`);
	lines.push(`    val textColor = Color(1f, 1f, 1f, 1f)`);
	lines.push(`    private val layout = GlyphLayout()`);
	lines.push(`    var alignment: Int = Align.left`);
	lines.push(`        set(value) {`);
	lines.push(`            field = value`);
	lines.push(`            updateSize()`);
	lines.push(`        }`);
	lines.push("");
	lines.push(`    init {`);
	lines.push(`        updateSize()`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    fun setText(newText: CharSequence) {`);
	lines.push(`        this.text = newText`);
	lines.push(`        updateSize()`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    fun setFontScale(scale: Float) {`);
	lines.push(`        font.data.setScale(scale)`);
	lines.push(`        updateSize()`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    private fun updateSize() {`);
	lines.push(`        layout.setText(font, text, textColor, 0f, alignment, false)`);
	lines.push(`        setSize(layout.width, layout.height)`);
	lines.push(`    }`);
	lines.push("");
	lines.push(`    override fun draw(batch: Batch, parentAlpha: Float) {`);
	lines.push(`        val prev = font.color.cpy()`);
	lines.push(`        font.color = Color(textColor.r, textColor.g, textColor.b, textColor.a * parentAlpha)`);
	lines.push(`        font.draw(batch, text, x, y + height, 0f, alignment, false)`);
	lines.push(`        font.color = prev`);
	lines.push(`    }`);
	lines.push(`}`);
	lines.push("");

	return lines.join("\n");
}

export function generateLabelActorFile(options: GenerateOptions): { fileName: string; content: string } {
	const ext = options.language === "java" ? "java" : "kt";
	const content = options.language === "java" ? generateLabelActorJava(options.helperPackageName) : generateLabelActorKotlin(options.helperPackageName);

	return {
		fileName: `LabelActor.${ext}`,
		content,
	};
}
